repos:
  # Appsec hook is MANDATORY, DO NOT comment it.
  - repo: https://github.com/despegar/git-hooks-scripts
    rev: v0.0.1
    hooks:
      - id: pre_commit_bash
        stages: [commit]
      #- id: pre_commit_python
      #  stages: [commit]

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
      - id: check-yaml